### PR TITLE
Add ootb RPi SD "support"

### PR DESCRIPTION
**Pull request by blaggacao**
Example of #72 &mdash; since this is potentially out of scope for nixflk, I'm leaving it as draft for others to discover how I solved it. Maybe some aspets can inform nixflk, though (like renaming niximg to nixISO, or such).

### CODE REVIEW

**Comment by blaggacao** [comment]
latest kernel support [got merged in master](https://github.com/NixOS/nixpkgs/pull/108975#event-4188675455), so the patches are no more necesary

**Comment by blaggacao** [comment]
Ok, so:

```console
$ nix develop
$ flk sd
```
fails with (what the heck?)
```console
/nix/store/fy819ys8fyzm02bjvzfvr7qiihr4allh-flk-env/bin/nix: line 2: 104701 Segmentation fault      (core dumped) /nix/store/6b7s5f2vrlixmlyr9bi1gkrgkq6xqgmw-nix-2.4pre20201205_a5d85d0/bin/nix --option experimental-features "nix-command flakes ca-references" "$@"
```

But on a similar structured repo, it fails with:
```console
Package ‘raspberrypi-firmware-1.20200601’ in /nix/store/vc3v85pjs6v04wn5w03z1b0mkl6r0p5q-source/pkgs/os-specific/linux/firmware/raspberrypi/default.nix:20 is not supported on ‘x86_64-linux’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

I'm concluding that cross compilation is not supported to date in nixflk.

**Comment by nrdxp** [comment]
I haven't messed with cross compilation in general in `nix`. So while I wouldn't mind including support for it in nixflk, we'd need someone more experience to implement it.

**Comment by mohe2015** [comment]
@blaggacao The radical but easiest way would likely to be: https://gist.github.com/mohe2015/3baaf764264f7bb9630bbe18dbdb6d8b/revisions (sorry for the not perfect diff, I just used my local version). This changes the build path to e.g. build with `nix build .#nixosConfigurations.aarch64-linux.nixSD.config.system.build.toplevel`. This doesn't really cross-compile but uses qemu binfmt emulation but I don't think this is even possible otherwise.

**Comment by nrdxp** [comment]
This seems to be supplanted by your #105, can I close?

**Pull request closed without merging**
