### PR TITLE
doc: begin work on new documentation

### LINKED ISSUE #111: revamp docs
We need a more thorough mechanism for documentation covering the following bases:
- [ ] all library functions
- [ ] profile blurbs
- [x] repo layout description
- [x] flk command
- [ ] user blurbs
- [ ] common examples of various actions
- [ ] various integration docs
  - [x] deploy-rs
  - [ ] NUR
  - [ ] devshell

Tracking #113

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96566403-revamp-docs?utm_campaign=plugin&utm_content=tracker%2F161955272&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F161955272&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nrdxp**
The scope of this PR has been reduced, and doesn't complete #111, but only partially implements it.

Essentially, each subdirectory will contain it's own README.md file explaining the purpose and usage of said directory. In additional,all of the md files will be compiled together in an mdbook which willbe rendered and hosted on github pages.

The rendered mdbook can be viewed on my website. https://nrdxp.dev/nixflk

### CODE REVIEW

**Comment by blaggacao** [comment]
Congrats! This is getting very nice!

**Comment by Pacman99** [comment]
I've read through the entire thing and it looks really great! I think it is very clear and easy to understand.

>It might be slightly advantageous to put layout markdown files directly alongside the respectifv nix files within the folder layout. This way, the md doc is directly available next to the relevant files (for example also for browsing git).

I would personally prefer this. It would be simpler and easy to contribute to. But I could see it being harder for you to maintain.

**Comment by nrdxp** [comment]
Sounds like a good idea. Still have a lot of work to do here, so I'll give it a shot and see how it goes.

**Comment by nrdxp** [comment]
force pushed, with layout section done, any everything squashed into a single commit.

**Comment by nrdxp** [comment]
I'm gonna go ahead and push this to core even though all the goals from #111 have not been reached. What we have so far will be immensely helpful for new users, and I'd like to get it in front of them right away. We will finish the issue with an additional PR in the future.

**Pull request merged**
